name: flutter_fastotv_common
author: Alexandr Topilski <support@fastogt.com>
description: Common files for FastoTV project
version: 1.1.0

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  cached_network_image: ^2.3.3
  dart_chromecast: ^0.2.4
  flutter_vlc_player:
    git:
      url: https://github.com/fastogt/flutter_vlc_player.git
      ref: master
  video_player:
    git:
      url: https://github.com/topilski/plugins.git
      ref: master
      path: packages/video_player/video_player

  flutter_mdns_plugin:
    git:
      url: https://github.com/terrabythia/flutter_mdns_plugin.git
      ref: master

  flutter_common:
    git:
      url: https://github.com/fastogt/flutter_common.git
      ref: master
