name: flutter_fastotv_common
author: Alexandr Topilski <support@fastogt.com>
description: Common files for FastoTV project
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  cached_network_image: ^2.0.0
  dart_chromecast: ^0.1.2
  intl: ^0.16.0
  video_player: ^0.10.9+1

  flutter_mdns_plugin:
    git:
      url: https://github.com/terrabythia/flutter_mdns_plugin.git
      ref: master

  fastotv_common:
    git:
      url: https://github.com/fastogt/flutter_common.git
      ref: master

  fastotv_dart:
    git:
      url: https://github.com/fastogt/fastotv_dart.git
      ref: master
